#!/bin/sh

LOG_FILE="/var/log/messages"

start() {
	# compress existing logs
	rm -f ${LOG_FILE}.gz
	gzip ${LOG_FILE}
}

stop() {
	echo "Can't stop..."
}

restart() {
        stop
        sleep 1
        start
}

case "$1" in
        start|stop|restart)
                "$1";;
        reload)
                # Restart, since there is no true "reload" feature.
                restart;;
        *)
                echo "Usage: $0 {start|stop|restart|reload}"
                exit 1
esac
